name: Node Integrate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: "config.json"
          json: '{"server":{"port": 5700, "type": "dev"}, "twitter":{"bearer_token": "${{ secrets.BEARER_TOKEN }}", "API_KEY": "${{ secrets.API_KEY }}"}, "postgres": {"password": "${{ secrets.POSTGRES }}"}}'
      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
      - name: Run the app
        run: yarn start
