name: Node Integrate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
      - name: Run the app
        run: yarn start
        with:
          config-file: config.json
